# general
E_NO_ERROR = "E_NO_ERROR"
E_INTERNAL_ERROR = "E_INTERNAL_ERROR"
E_WRONG_REQUEST = "E_WRONG_REQUEST"

# access
E_AUTHORIZATION_REQUIRED = "E_AUTHORIZATION_REQUIRED"
E_SESSION_NOT_FOUND = "E_SESSION_NOT_FOUND"
E_LOGIN_FAILED = "E_LOGIN_FAILED"
E_ACCESS_DENIED = "E_ACCESS_DENIED"
E_ADMIN_REQUIRED = "E_ADMIN_REQUIRED"
E_SYSTEM_ADMIN_REQUIRED = "E_SYSTEM_ADMIN_REQUIRED"
E_CLIENT_ACCOUNT_REQUIRED = "E_CLIENT_ACCOUNT_REQUIRED"
E_DEVICE_COOKIE_LOCKOUT = "E_DEVICE_COOKIE_LOCKOUT"
E_DEVICE_COOKIE_INVALID = "E_DEVICE_COOKIE_INVALID"

# Security: CSRF
E_CSRF_TOKEN_MISSING = "E_CSRF_TOKEN_MISSING"
E_CSRF_TOKEN_MISMATCH = "E_CSRF_TOKEN_MISMATCH"
E_CSRF_TOKEN_INVALID = "E_CSRF_TOKEN_INVALID"
E_CSRF_TOKEN_USER_MISMATCH = "E_CSRF_TOKEN_USER_MISMATCH"

# user
E_USER_NOT_FOUND = "E_USER_NOT_FOUND"
E_USER_EXISTS = "E_USER_EXISTS"
E_USER_NOT_DELETED = "E_USER_NOT_DELETED"
E_USER_DELETED = "E_USER_DELETED"
E_USER_BEING_ERASED = "E_USER_BEING_ERASED"
E_ACCOUNT_NOT_CONFIRMED = "E_ACCOUNT_NOT_CONFIRMED"
E_ACCOUNT_DISABLED = "E_ACCOUNT_DISABLED"
E_WRONG_PASSWORD = "E_WRONG_PASSWORD"

# project
E_PROJECT_NOT_FOUND = "E_PROJECT_NOT_FOUND"
E_PROJECT_EXISTS = "E_PROJECT_EXISTS"
E_PROJECT_DELETED = "E_PROJECT_DELETED"
E_PROJECT_NOT_DELETED = "E_PROJECT_NOT_DELETED"
E_PROJECT_BEING_ERASED = "E_PROJECT_BEING_ERASED"
E_POOL_NOT_FOUND = "E_POOL_NOT_FOUND"
E_POOL_EXISTS = "E_POOL_EXISTS"
E_POOL_LOCKED = "E_POOL_LOCKED"
E_DEFAULT_PROJECT_IMMUTABLE = "E_DEFAULT_PROJECT_IMMUTABLE"
E_PROJECT_DELETE_ERROR = "E_PROJECT_DELETE_ERROR"
E_CPU_RAM_MULTIPLICITY_BROKEN = "E_CPU_RAM_MULTIPLICITY_BROKEN"
E_NODE_CPU_INVALID = "E_NODE_CPU_INVALID"
E_NODE_RAM_INVALID = "E_NODE_RAM_INVALID"
E_INVALID_MEM_PER_CORE = "E_INVALID_MEM_PER_CORE"

# pool
E_INVALID_NODE_GROUP = "E_INVALID_NODE_GROUP"

# fuzzer
E_FUZZER_NOT_FOUND = "E_FUZZER_NOT_FOUND"
E_FUZZER_EXISTS = "E_FUZZER_EXISTS"
E_FUZZER_DELETED = "E_FUZZER_DELETED"
E_FUZZER_NOT_DELETED = "E_FUZZER_NOT_DELETED"
E_FUZZER_BEING_ERASED = "E_FUZZER_BEING_ERASED"
E_FUZZER_LANG_MISMATCH = "E_FUZZER_LANG_MISMATCH"
E_FUZZER_ENGINE_MISMATCH = "E_FUZZER_ENGINE_MISMATCH"
E_FUZZER_NOT_IN_TRASHBIN = "E_FUZZER_NOT_IN_TRASHBIN"
E_ACTIVE_REVISION_NOT_FOUND = "E_ACTIVE_REVISION_NOT_FOUND"

# revision
E_REVISION_NOT_FOUND = "E_REVISION_NOT_FOUND"
E_REVISION_EXISTS = "E_REVISION_EXISTS"
E_REVISION_DELETED = "E_REVISION_DELETED"
E_REVISION_NOT_DELETED = "E_REVISION_NOT_DELETED"
E_REVISION_BEING_ERASED = "E_REVISION_BEING_ERASED"
E_REVISION_CAN_NOT_BE_CHANGED = "E_REVISION_CAN_NOT_BE_CHANGED"
E_REVISION_IS_NOT_RUNNING = "E_REVISION_IS_NOT_RUNNING"
E_REVISION_CAN_ONLY_RESTART = "E_REVISION_CAN_ONLY_RESTART"
E_REVISION_ALREADY_RUNNING = "E_REVISION_ALREADY_RUNNING"
E_MUST_UPLOAD_BINARIES = "E_MUST_UPLOAD_BINARIES"
E_REVISION_ALREADY_ACTIVE = "E_REVISION_ALREADY_ACTIVE"
E_NO_POOL_TO_USE = "E_NO_POOL_TO_USE"
E_CPU_USAGE_INVALID = "E_CPU_USAGE_INVALID"
E_RAM_USAGE_INVALID = "E_RAM_USAGE_INVALID"
E_TMPFS_SIZE_INVALID = "E_TMPFS_SIZE_INVALID"
E_TOTAL_RAM_USAGE_INVALID = "E_TOTAL_RAM_USAGE_INVALID"
E_SOURCE_REVISION_NOT_FOUND = "E_SOURCE_REVISION_NOT_FOUND"
E_TARGET_REVISION_NOT_FOUND = "E_TARGET_REVISION_NOT_FOUND"
E_CORPUS_OVERWRITE_FORBIDDEN = "E_CORPUS_OVERWRITE_FORBIDDEN"
E_NO_CORPUS_FOUND = "E_NO_CORPUS_FOUND"
E_COPY_SOURCE_TARGET_SAME = "E_COPY_SOURCE_TARGET_SAME"

# image
E_IMAGE_NOT_FOUND = "E_IMAGE_NOT_FOUND"
E_IMAGE_EXISTS = "E_IMAGE_EXISTS"
E_IMAGE_NOT_READY = "E_IMAGE_NOT_READY"
E_ENGINE_LANG_INCOMPATIBLE = "E_ENGINE_LANG_INCOMPATIBLE"

# engines
E_ENGINE_NOT_FOUND = "E_ENGINE_NOT_FOUND"
E_ENGINE_EXISTS = "E_ENGINE_EXISTS"
E_ENGINE_LANG_NOT_ENABLED = "E_ENGINE_LANG_NOT_ENABLED"
E_ENGINE_LANG_ALREADY_ENABLED = "E_ENGINE_LANG_ALREADY_ENABLED"
E_ENGINES_INVALID = "E_ENGINES_INVALID"
E_ENGINE_IN_USE_BY = "E_ENGINE_IN_USE_BY"

# langs
E_LANG_NOT_FOUND = "E_LANG_NOT_FOUND"
E_LANG_EXISTS = "E_LANG_EXISTS"
E_LANGS_INVALID = "E_LANGS_NOT_FOUND"
E_LANG_IN_USE_BY = "E_LANG_IN_USE_BY"

# integration
E_INTEGRATION_NOT_FOUND = "E_INTEGRATION_NOT_FOUND"
E_INTEGRATION_EXISTS = "E_INTEGRATION_EXISTS"
E_INTEGRATION_TYPE_MISMATCH = "E_INTEGRATION_TYPE_MISMATCH"

# integration type
E_INTEGRATION_TYPE_NOT_FOUND = "E_INTEGRATION_TYPE_NOT_FOUND"
E_INTEGRATION_TYPE_EXISTS = "E_INTEGRATION_TYPE_NOT_FOUND"
E_INTEGRATION_TYPE_IN_USE_BY = "E_INTEGRATION_TYPE_IN_USE_BY"

# crash
E_CRASH_NOT_FOUND = "E_CRASH_NOT_FOUND"

# statistics
E_STATISTICS_NOT_FOUND = "E_STATISTICS_NOT_FOUND"

# files
E_UPLOAD_FAILURE = "E_UPLOAD_FAILURE"
E_FILE_NOT_FOUND = "E_FILE_NOT_FOUND"
E_FILE_TOO_LARGE = "E_FILE_TOO_LARGE"
E_FILE_NOT_ARCHIVE = "E_FILE_NOT_ARCHIVE"
E_JSON_FILE_IS_INVALID = "E_JSON_FILE_IS_INVALID"
